services:

  web-api:
    image: openjdk:21-jdk-slim
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-api
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/avitodb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1
      - SERVER_PORT=9080
    ports:
      - "8080:8080"
    depends_on:
      - postgres
#      postgres:
#        condition: service_healthy
#
#  keycloak:
#    image: quay.io/keycloak/keycloak:latest
#    container_name: keycloak
#    environment:
##      - KEYCLOAK_ADMIN_USERNAME=admin
##      - KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD=admin
#      - KEYCLOAK_ADMIN=admin
#      - KEYCLOAK_ADMIN_PASSWORD=admin
#      - KC_DB=postgres
#      - KC_DB_URL=jdbc:postgresql://postgres:5432/avitodb
#      - KC_DB_USERNAME=postgres
#      - KC_DB_PASSWORD=1
#      - KC_HOSTNAME=localhost
#      - KC_HOSTNAME_PORT=8080
#      - KC_HOSTNAME_STRICT=false
#      - KC_LOG_LEVEL=info
#      - KC_PROXY=edge
#    ports:
#      - "8095:8080"
#    depends_on:
#      - postgres
#    command: start-dev

  postgres:
    image: postgres
    container_name: avitodb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: avitodb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
#
#  zookeeper:
#    image: confluentinc/cp-zookeeper:7.4.0
#    hostname: zookeeper
#    container_name: zookeeper
#    ports:
#      - "2181:2181"
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#    networks:
#      - kafka-net
#
#  kafka:
#    image: confluentinc/cp-kafka:7.4.0
#    hostname: kafka
#    container_name: kafka
#    depends_on:
#      - zookeeper
#    ports:
#      - "9092:9092"
#      - "29092:29092"
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
#    networks:
#      - kafka-net
#
#  kafka-ui:
#    image: provectuslabs/kafka-ui:latest
#    container_name: kafka-ui
#    depends_on:
#      - kafka
#    ports:
#      - "8090:8080"
#    environment:
#      KAFKA_CLUSTERS_0_NAME: local
#      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
#      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
#    networks:
#      - kafka-net
#
#networks:
#  kafka-net:
#    driver: bridge

volumes:
  postgres_data: