logging:
    level:
        com:
            example: DEBUG
        org:
            hibernate:
                SQL: INFO
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE
            root: INFO
            springframework:
                security: DEBUG

spring:
    application:
        name: avitorest1
    datasource:
        driverClassName: org.postgresql.Driver
        password: 1
        url: jdbc:postgresql://localhost:5432/avitodb
        username: postgres
    flyway:
        baseline-on-migrate: true
        baseline-version: 1
        enabled: true
        locations: classpath:db/migration
        placeholders:
            schema: public
        schemas: public
    jackson:
        serialization:
            FAIL_ON_EMPTY_BEANS: false
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                transaction:
                  jta:
                      platform: org.hibernate.engine.transaction.jta.platform.NoJtaPlatform
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: false
springdoc:
    swagger-ui:
        enabled: true
        operationsSorter: alpha
        path: /
        tagsSorter: alpha
server:
    port: 9080
    servlet:
        context-path: /

app:
  jwt-secret: "c8bea761d1d42bf828c42b9e0cdbe23f490b58a67828ab30231ad965caf12f52"
  jwt-expiration-milliseconds: 604800000
