CREATE TABLE authors
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(100)                            NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    role       VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    money      DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_authors PRIMARY KEY (id)
);

CREATE TABLE posts
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    price       INTEGER                                 NOT NULL,
    category    VARCHAR(255)                            NOT NULL,
    date        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    author_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_posts PRIMARY KEY (id)
);

ALTER TABLE authors
    ADD CONSTRAINT uc_authors_email UNIQUE (email);

ALTER TABLE posts
    ADD CONSTRAINT FK_POSTS_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES authors (id);