CREATE TABLE authors
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(100)                            NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    role       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_authors PRIMARY KEY (id)
);

CREATE TABLE posts
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    post_name   VARCHAR(100)                            NOT NULL,
    category    VARCHAR(100)                            NOT NULL,
    description VARCHAR(255),
    posted_at   TIMESTAMP WITHOUT TIME ZONE,
    price       INTEGER,
    author_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_posts PRIMARY KEY (id)
);

ALTER TABLE posts
    ADD CONSTRAINT uc_48effacd2306e5983c7423fe8 UNIQUE (id);

ALTER TABLE authors
    ADD CONSTRAINT uc_authors_email UNIQUE (email);

ALTER TABLE posts
    ADD CONSTRAINT FK_POSTS_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES authors (id);